// SPDX-License-Identifier: EUPL-1.2

import { defineStore } from 'pinia';

export const useMockStore = defineStore('mock', {
  state: () => ({
    getDocuments: {
      request: {
        id: 'string',
        func: 'getDocuments',
        data: {},
      },
      response: {
        id: 'string',
        status: 'SUCCESS',
        data: {
          documents: [
            {
              meta: {
                id: 'Document_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                issuanceState: 'Issued',
                type: 'PID',
                hasExpired: false,
                isFavorite: false,
                expirationDate: '2025-05-20',
                issuingAuthority: 'PMLP',
                issuerCountry: 'LV',
                issuanceDate: '2025-02-19',
                displayNumber: '32015372306',
                description: null,
                additionalInfo: '',
              },
            },
            {
              meta: {
                id: 'Document_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                issuanceState: 'Issued',
                type: 'mDL',
                hasExpired: false,
                isFavorite: true,
                expirationDate: '2025-02-26',
                issuingAuthority: 'CSDD',
                issuerCountry: 'LV',
                issuanceDate: '2025-02-19',
                displayNumber: 'WE000109',
                description: 'LV',
                additionalInfo: 'B, BE, C, CE, D',
              },
            },
            {
              meta: {
                id: 'Document_EudiWalletDocumentManager_2d78b8b7-94ad-4d2e-a82b-90b9098c61c1',
                issuanceState: 'Issued',
                type: 'Diploma',
                hasExpired: false,
                isFavorite: true,
                expirationDate: '',
                issuingAuthority: 'RTU',
                issuerCountry: 'LV',
                issuanceDate: '2024-11-04T12:05:52+01:00',
                displayNumber: '320153-72306',
                description:
                  'Mechanics and Metal Processing, Heat Power Engineering, Heat Technology, and Mechanical Engineering',
                additionalInfo: 'Bachelor degree of engineering science in mechanical engineering',
              },
            },
            {
              meta: {
                id: 'Document_EudiWalletDocumentManager_a67bd590-b31d-4348-b60e-54b31e5da796',
                issuanceState: 'Issued',
                type: 'eSign',
                hasExpired: false,
                isFavorite: true,
                expirationDate: '2025-11-04T12:05:52+01:00',
                issuingAuthority: '',
                issuerCountry: '',
                issuanceDate: '2024-11-04T12:05:52+01:00',
                displayNumber: '545353543',
                description: '',
                additionalInfo: '',
              },
            },
            {
              meta: {
                id: 'Document_EudiWalletDocumentManager_a67bd590-b31d-4348-b60e-54b31e5da755',
                issuanceState: 'Issued',
                type: 'eSeal',
                hasExpired: false,
                isFavorite: true,
                expirationDate: '2025-11-04T12:05:52+01:00',
                issuingAuthority: '',
                issuerCountry: '',
                issuanceDate: '2024-11-04T12:05:52+01:00',
                displayNumber: '545353543',
                description: '',
                additionalInfo: '',
              },
            },
            {
              meta: {
                id: 'Document_EudiWalletDocumentManager_e5438957-23ed-4ebc',
                issuanceState: 'Issued',
                type: 'IBAN',
                hasExpired: false,
                isFavorite: true,
                expirationDate: '',
                issuingAuthority: 'SEB',
                issuerCountry: 'LV',
                issuanceDate: '',
                displayNumber: 'LV58UNLA0050000005627',
                description: '',
                additionalInfo: '',
              },
            },
          ],
        },
      },
    },
    getDocumentDetails: {
      response: [
        {
          id: 'string',
          status: 'SUCCESS',
          data: {
            meta: {
              id: 'Document_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
              issuanceState: 'Issued',
              type: 'PID',
              hasExpired: false,
              isFavorite: false,
              expirationDate: '2025-05-20',
              issuingAuthority: 'PMLP',
              issuerCountry: 'LV',
              issuanceDate: '2025-02-19',
              displayNumber: '32015372306',
              description: 'LV',
              additionalInfo: '',
            },
            documentDetails: [
              {
                type: 'default',
                identifier: 'age_over_18',
                label: 'Age Over 18',
                value: 'true', // 'true', 'false'
              },
              {
                type: 'default',
                identifier: 'expiry_date',
                label: 'Expiry Date',
                value: '2025-04-29',
              },
              {
                type: 'default',
                identifier: 'issuing_country',
                label: 'Issuing Country',
                value: 'LV',
              },
              {
                type: 'default',
                identifier: 'issuance_date',
                label: 'Issuance Date',
                value: '2025-01-29',
              },
              {
                type: 'default',
                identifier: 'given_name',
                label: 'Given Name(s)',
                value: 'MĀRA',
              },
              {
                type: 'default',
                identifier: 'issuing_authority',
                label: 'Issuance Authority',
                value: 'PMLP',
              },
              {
                type: 'default',
                identifier: 'birth_date',
                label: 'Birth Date',
                value: '1982-12-12',
              },
              {
                type: 'default',
                identifier: 'nationality',
                label: 'Nationality',
                value: 'LV',
              },
              {
                type: 'default',
                identifier: 'personal_administrative_number',
                label: 'Person unique personal administrative number',
                value: '32015372306',
              },
              {
                type: 'default',
                identifier: 'birth_country',
                label: 'Birth Country',
                value: 'AI',
              },
              {
                type: 'default',
                identifier: 'family_name',
                label: 'Family Name(s)',
                value: 'PARAUDZIŅA',
              },
              {
                type: 'default',
                identifier: 'birth_place',
                label: 'Birth Place',
                value: 'ANGILJA',
              },
            ],
          },
        },
        {
          id: 'string',
          status: 'SUCCESS',
          data: {
            meta: {
              id: 'Document_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
              issuanceState: 'Issued',
              type: 'mDL',
              hasExpired: false,
              isFavorite: false,
              expirationDate: '2025-02-26',
              issuingAuthority: 'CSDD',
              issuerCountry: 'LV',
              issuanceDate: '2025-02-19',
              displayNumber: 'WE000109',
              description: 'LV',
              additionalInfo: 'B, BE, C, CE, D',
            },
            documentDetails: [
              {
                type: 'default',
                identifier: 'un_distinguishing_sign',
                label: 'UN distinguishing sign',
                value: 'LV',
              },
              {
                type: 'default',
                identifier: 'driving_privileges',
                label: 'Categories of vehicles',
                value: 'B, BE, C, CE, D',
              },
              {
                type: 'default',
                identifier: 'expiry_date',
                label: 'Date when mDL expires',
                value: '2025-02-05',
              },
              {
                type: 'default',
                identifier: 'document_number',
                label: 'Licence number',
                value: 'WE000109',
              },
              {
                type: 'default',
                identifier: 'personal_administrative_number',
                label: 'Person unique personal administrative number',
                value: '32015372306',
              },
              {
                type: 'default',
                identifier: 'age_over_18',
                label: 'Age attestation: Nearest “true” attestation above request',
                value: 'false',
              },
              {
                type: 'default',
                identifier: 'given_name',
                label: 'Given names',
                value: 'SANDAMU HASIKA RATHMALGODA',
              },
              {
                type: 'default',
                identifier: 'issuing_country',
                label: 'Issuing country',
                value: 'LV',
              },
              {
                type: 'default',
                identifier: 'issue_date',
                label: 'Date of issue',
                value: '2025-01-29',
              },
              {
                type: 'default',
                identifier: 'birth_date',
                label: 'Date of birth',
                value: '1965-02-15',
              },
              {
                type: 'default',
                identifier: 'family_name',
                label: 'Family name',
                value: 'RATHMALSODA HERANISE MIDIANSEHANU',
              },
              {
                type: 'default',
                identifier: 'issuing_authority',
                label: 'Issuing authority',
                value: 'Test QEAA issuer',
              },
              {
                type: 'default',
                identifier: 'portrait',
                label: 'Portrait of mDL holder',
                value: 'Shown above',
              },
            ],
          },
        },
        {
          id: 'string',
          status: 'SUCCESS',
          data: {
            meta: {
              id: 'Document_EudiWalletDocumentManager_2d78b8b7-94ad-4d2e-a82b-90b9098c61c1',
              issuanceState: 'Issued',
              type: 'Diploma',
              hasExpired: false,
              isFavorite: false,
              expirationDate: '',
              issuingAuthority: 'RTU',
              issuerCountry: 'LV',
              issuanceDate: '2024-11-04T12:05:52+01:00',
              displayNumber: '320153-72306',
              description:
                'Mechanics and Metal Processing, Heat Power Engineering, Heat Technology, and Mechanical Engineering',
              additionalInfo: 'Bachelor degree of engineering science in mechanical engineering',
            },
            documentImage: '',
            documentDetails: [
              {
                type: 'default',
                identifier: 'awardingBody_countryCode',
                label: 'Awarding body country code',
                value: 'LV',
              },
              {
                type: 'default',
                identifier: 'familyName',
                label: 'The family name of the person',
                value: 'Paraudziņa',
              },
              {
                type: 'default',
                identifier: 'issuing_authority',
                label: 'Issuing authority',
                value: 'RTU',
              },
              {
                type: 'default',
                identifier: 'creditValue',
                label: 'Credit system',
                value: 'ECTS',
              },
              {
                type: 'default',
                identifier: 'eqfLevel',
                label: 'EQF level',
                value: 'Level 6',
              },
              {
                type: 'default',
                identifier: 'nationalID',
                label: 'The national identifier of the person',
                value: '320153-72306',
              },
              {
                type: 'default',
                identifier: 'thematicArea',
                label: 'Thematic area',
                value:
                  'Mechanics and Metal Processing, Heat Power Engineering, Heat Technology, and Mechanical Engineering',
              },
              {
                type: 'default',
                identifier: 'citizenshipCountryCode',
                label: 'Citizenship country code',
                value: 'LV',
              },
              {
                type: 'default',
                identifier: 'awardingBody_legalName',
                label: 'Awarded by',
                value: 'Rīgas Tehniskā universitāte',
              },
              {
                type: 'default',
                identifier: 'validFrom',
                label: 'Valid from',
                value: '2024-06-20T00:00:00+03:00',
              },
              {
                type: 'default',
                identifier: 'maximumDuration',
                label: 'Maximum duration in months',
                value: 'P36M',
              },
              {
                type: 'default',
                identifier: 'title',
                label: 'Achievement title',
                value: 'Bachelor degree of engineering science in mechanical engineering',
              },
              {
                type: 'default',
                identifier: 'creditPoint',
                label: 'ECTS',
                value: '240',
              },
              {
                type: 'default',
                identifier: 'awardingBody_registration',
                label: 'The legal identifier of the awarding body',
                value: '90000068977',
              },
              {
                type: 'default',
                identifier: 'issuanceDate',
                label: 'Issuance date',
                value: '2024-11-04T12:05:52+01:00',
              },
              {
                type: 'default',
                identifier: 'nqfLevel',
                label: 'NQF level',
                value: 'LQF Level 6',
              },
              {
                type: 'default',
                identifier: 'type',
                label: 'The type of credential',
                value: 'LearningAchievement',
              },
              {
                type: 'default',
                identifier: 'issued',
                label: 'Issuance date',
                value: '2024-11-04T12:05:52+01:00',
              },
              {
                type: 'default',
                identifier: 'givenName',
                label: 'The given name(s) of the person',
                value: 'Māra',
              },
            ],
          },
        },
        {
          id: 'string',
          status: 'SUCCESS',
          data: {
            meta: {
              id: 'Document_EudiWalletDocumentManager_a67bd590-b31d-4348-b60e-54b31e5da796',
              issuanceState: 'Issued',
              type: 'eSign',
              hasExpired: false,
              isFavorite: true,
              expirationDate: '2025-11-04T12:05:52+01:00',
              issuingAuthority: '',
              issuerCountry: '',
              issuanceDate: '2024-11-04T12:05:52+01:00',
              displayNumber: '545353543',
              description: '',
              additionalInfo: '',
            },
            documentImage: '',
            documentDetails: [
              {
                type: 'default',
                identifier: 'sid',
                label: 'sid',
                value: 'cZ5OztvziLYzhKFdsuL5pC-4z_Q',
              },
              {
                type: 'default',
                identifier: 'cn',
                label: 'cn',
                value: 'MĀRA PARAUDZIŅA',
              },
              {
                type: 'default',
                identifier: 'expiresOn',
                label: 'expiresOn',
                value: '2028-03-05T09:49:10',
              },
              {
                type: 'default',
                identifier: 'issuedOn',
                label: 'issuedOn',
                value: '2025-03-05T09:49:10',
              },
              {
                type: 'default',
                identifier: 'type',
                label: 'type',
                value: 'eSign',
              },
            ],
          },
        },
        {
          id: 'string',
          status: 'SUCCESS',
          data: {
            meta: {
              id: 'Document_EudiWalletDocumentManager_a67bd590-b31d-4348-b60e-54b31e5da755',
              issuanceState: 'Issued',
              type: 'eSeal',
              hasExpired: false,
              isFavorite: true,
              expirationDate: '2025-11-04T12:05:52+01:00',
              issuingAuthority: '',
              issuerCountry: '',
              issuanceDate: '2024-11-04T12:05:52+01:00',
              displayNumber: '545353543',
              description: '',
              additionalInfo: '',
            },
            documentImage: '',
            documentDetails: [
              {
                type: 'default',
                identifier: 'sid',
                label: 'sid',
                value: 'cZ5OztvziLYzhKFdsuL5pC-4z_Q',
              },
              {
                type: 'default',
                identifier: 'cn',
                label: 'cn',
                value: 'SIA DEMO QSEAL: eZīmogs',
              },
              {
                type: 'default',
                identifier: 'expiresOn',
                label: 'expiresOn',
                value: '2028-03-05T09:49:10',
              },
              {
                type: 'default',
                identifier: 'issuedOn',
                label: 'issuedOn',
                value: '2025-03-05T09:49:10',
              },
              {
                type: 'default',
                identifier: 'type',
                label: 'type',
                value: 'eSeal',
              },
            ],
          },
        },
        {
          id: 'string',
          status: 'SUCCESS',
          data: {
            meta: {
              id: 'Document_EudiWalletDocumentManager_a67bd590-b31d-4348-b60e-54b31e5da7556',
              issuanceState: 'Issued',
              type: 'payment',
              hasExpired: false,
              isFavorite: true,
              expirationDate: '2025-11-04T12:05:52+01:00',
              issuingAuthority: 'SEB',
              issuerCountry: '',
              issuanceDate: '2024-11-04T12:05:52+01:00',
              displayNumber: 'LV88 UNLA 0055 0001 4440 3',
              description: '',
              additionalInfo: '',
            },
            documentImage: '',
            documentDetails: [],
          },
        },
        {
          id: 'string',
          status: 'SUCCESS',
          data: {
            meta: {
              id: 'Document_EudiWalletDocumentManager_2d78b8b7-94ad-4d2e-a82b-90b9098c61c2',
              issuanceState: 'Issued',
              type: 'Signature',
              hasExpired: false,
              isFavorite: false,
              expirationDate: '',
              issuingAuthority: 'RTU',
              issuerCountry: 'LV',
              issuanceDate: '2024-11-04T12:05:52+01:00',
              displayNumber: '320153-72306',
              description: 'Signature',
            },
            documentImage: '',
            documentDetails: [],
          },
        },
        {
          id: 'string',
          status: 'SUCCESS',
          data: {
            meta: {
              id: 'Document_EudiWalletDocumentManager_e5438957-23ed-4ebc',
              type: 'IBAN',
              issuanceState: 'Issued',
              hasExpired: false,
              expirationDate: '',
              issuingAuthority: 'SEB',
              issuerCountry: '',
              issuanceDate: '',
              displayNumber: 'LV58UNLA0050000005627',
            },
            documentDetails: [
              {
                type: 'default',
                identifier: 'business_identifier_code',
                label: 'Business Identifier Code',
                value: 'UNLALV2X',
              },
              {
                type: 'default',
                identifier: 'account_name',
                label: 'Account Name',
                value: 'Jānis Bērziņš',
              },
              {
                type: 'default',
                identifier: 'iban',
                label: 'IBAN',
                value: 'LV58UNLA0050000005627',
              },
              {
                type: 'default',
                identifier: 'registered_family_name',
                label: 'Registered Family Name',
                value: 'Bērziņš',
              },
              {
                type: 'default',
                identifier: 'registered_given_name',
                label: 'Registered Given Name',
                value: 'Jānis',
              },
              {
                type: 'default',
                identifier: 'currency',
                label: 'Currency',
                value: 'EUR',
              },
              {
                type: 'default',
                identifier: 'iat',
                label: 'iat',
                value: '2025-05-28 05:08:49',
              },
              {
                type: 'default',
                identifier: 'exp',
                label: 'exp',
                value: '2025-05-28 05:08:49',
              },
              {
                type: 'default',
                identifier: 'nbf',
                label: 'nbf',
                value: '2025-05-28 05:08:49',
              },
            ],
          },
        },
      ],
    },
    getDocumentOptions: {
      request: {
        id: 'string',
        func: 'getDocumentOptions',
        data: null,
      },
      response: {
        id: 'string',
        status: 'SUCCESS',
        data: {
          options: [
            {
              text: 'mDL',
              type: 'eu.europa.ec.eudi.mdl_mdoc',
              exists: 'false',
            },
            {
              text: 'PID',
              type: 'eu.europa.ec.eudi.pid_mdoc',
              exists: 'true',
            },
            {
              text: 'Diploma',
              type: 'eu.europa.ec.eudi.rtu_diploma_mdoc',
              exists: 'false',
            },
            {
              text: 'eSign',
              type: 'eSign',
              exists: 'false',
            },
            {
              text: 'eSeal',
              type: 'eSeal',
              exists: 'false',
            },
            {
              text: 'IBAN',
              type: 'IBAN',
              exists: 'false',
            },
          ],
        },
      },
    },
    getRequestDocuments: {
      request: {
        id: 'string',
        func: 'getRequestDocuments',
        data: null,
      },
      response: {
        id: 'string',
        status: 'SUCCESS',
        data: {
          verifierName: 'EUDI Remote Verifier',
          verifierIsTrusted: true,
          documents: [
            {
              fields: [
                {
                  checked: true,
                  elementIdentifier: 'family_name',
                  enabled: true,
                  id: 'family_nameDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'Family Name(s)',
                  value: 'PARAUDZIŅA',
                },
                {
                  checked: true,
                  elementIdentifier: 'given_name',
                  enabled: true,
                  id: 'given_nameDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'Given Name(s)',
                  value: 'MĀRA',
                },
                {
                  checked: true,
                  elementIdentifier: 'birth_date',
                  enabled: true,
                  id: 'birth_dateDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'Birth Date',
                  value: '1982-12-12',
                },
                {
                  checked: true,
                  elementIdentifier: 'age_over_18',
                  enabled: true,
                  id: 'age_over_18Document_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'Age Over 18',
                  value: 'true',
                },
                {
                  checked: false,
                  elementIdentifier: 'age_in_years',
                  enabled: false,
                  id: 'age_in_yearsDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'age_in_years',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'age_birth_year',
                  enabled: false,
                  id: 'age_birth_yearDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'age_birth_year',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'family_name_birth',
                  enabled: false,
                  id: 'family_name_birthDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'family_name_birth',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'given_name_birth',
                  enabled: false,
                  id: 'given_name_birthDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'given_name_birth',
                  value: 'Not available',
                },
                {
                  checked: true,
                  elementIdentifier: 'birth_place',
                  enabled: true,
                  id: 'birth_placeDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'Birth Place',
                  value: 'ANGILJA',
                },
                {
                  checked: true,
                  elementIdentifier: 'birth_country',
                  enabled: true,
                  id: 'birth_countryDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'Birth Country',
                  value: 'AI',
                },
                {
                  checked: false,
                  elementIdentifier: 'birth_state',
                  enabled: false,
                  id: 'birth_stateDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'birth_state',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'birth_city',
                  enabled: false,
                  id: 'birth_cityDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'birth_city',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_address',
                  enabled: false,
                  id: 'resident_addressDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'resident_address',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_country',
                  enabled: false,
                  id: 'resident_countryDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'resident_country',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_state',
                  enabled: false,
                  id: 'resident_stateDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'resident_state',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_city',
                  enabled: false,
                  id: 'resident_cityDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'resident_city',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_postal_code',
                  enabled: false,
                  id: 'resident_postal_codeDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'resident_postal_code',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_street',
                  enabled: false,
                  id: 'resident_streetDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'resident_street',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_house_number',
                  enabled: false,
                  id: 'resident_house_numberDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'resident_house_number',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'gender',
                  enabled: false,
                  id: 'genderDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'gender',
                  value: 'Not available',
                },
                {
                  checked: true,
                  elementIdentifier: 'nationality',
                  enabled: true,
                  id: 'nationalityDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: false,
                  readableName: 'Nationality',
                  value: 'LV',
                },
                {
                  checked: true,
                  elementIdentifier: 'issuance_date',
                  enabled: false,
                  id: 'issuance_dateDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: true,
                  readableName: 'Issuance Date',
                  value: '2025-01-29',
                },
                {
                  checked: true,
                  elementIdentifier: 'expiry_date',
                  enabled: false,
                  id: 'expiry_dateDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: true,
                  readableName: 'Expiry Date',
                  value: '2025-04-29',
                },
                {
                  checked: true,
                  elementIdentifier: 'issuing_authority',
                  enabled: false,
                  id: 'issuing_authorityDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: true,
                  readableName: 'Issuance Authority',
                  value: 'PMLP',
                },
                {
                  checked: false,
                  elementIdentifier: 'document_number',
                  enabled: false,
                  id: 'document_numberDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: true,
                  readableName: 'document_number',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'administrative_number',
                  enabled: false,
                  id: 'administrative_numberDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: true,
                  readableName: 'administrative_number',
                  value: 'Not available',
                },
                {
                  checked: true,
                  elementIdentifier: 'issuing_country',
                  enabled: false,
                  id: 'issuing_countryDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: true,
                  readableName: 'Issuing Country',
                  value: 'LV',
                },
                {
                  checked: false,
                  elementIdentifier: 'issuing_jurisdiction',
                  enabled: false,
                  id: 'issuing_jurisdictionDocument_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
                  isRequired: true,
                  readableName: 'issuing_jurisdiction',
                  value: 'Not available',
                },
              ],
              title: 'PID',
              // meta: {
              //   id: 'Document_EudiWalletDocumentManager_e5438957-23ed-4ebc-bd3d-72139879fe4e',
              //   type: 'PID',
              //   issuanceState: 'Issued',
              //   hasExpired: false,
              //   expirationDate: '2025-04-25',
              //   issuingAuthority: 'PMLP',
              //   issuerCountry: 'LV',
              //   issuanceDate: '2025-01-29',
              // },
              meta: {
                id: 'Document_EudiWalletDocumentManager_e5438957-23ed-4ebc',
                issuanceState: 'Issued',
                type: 'IBAN',
                hasExpired: false,
                isFavorite: true,
                expirationDate: '',
                issuingAuthority: 'SEB',
                issuerCountry: 'LV',
                issuanceDate: '',
                displayNumber: 'LV58UNLA0050000005627',
                description: '',
                additionalInfo: '',
              },
            },
            {
              fields: [
                {
                  checked: true,
                  elementIdentifier: 'family_name',
                  enabled: true,
                  id: 'family_nameDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Family name',
                  value: 'RATHMALSODA HERANISE MIDIANSEHANU',
                },
                {
                  checked: true,
                  elementIdentifier: 'given_name',
                  enabled: true,
                  id: 'given_nameDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Given names',
                  value: 'SANDAMU HASIKA RATHMALGODA',
                },
                {
                  checked: true,
                  elementIdentifier: 'birth_date',
                  enabled: true,
                  id: 'birth_dateDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Date of birth',
                  value: '1965-02-15',
                },
                {
                  checked: true,
                  elementIdentifier: 'issue_date',
                  enabled: true,
                  id: 'issue_dateDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Date of issue',
                  value: '2025-01-29',
                },
                {
                  checked: true,
                  elementIdentifier: 'expiry_date',
                  enabled: true,
                  id: 'expiry_dateDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Date when mDL expires',
                  value: '2025-02-05',
                },
                {
                  checked: true,
                  elementIdentifier: 'age_over_18',
                  enabled: true,
                  id: 'age_over_18Document_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Age attestation: Nearest “true” attestation above request',
                  value: 'true',
                },
                {
                  checked: false,
                  elementIdentifier: 'age_over_21',
                  enabled: false,
                  id: 'age_over_21Document_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'age_over_21',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'age_in_years',
                  enabled: false,
                  id: 'age_in_yearsDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'age_in_years',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'age_birth_year',
                  enabled: false,
                  id: 'age_birth_yearDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'age_birth_year',
                  value: 'Not available',
                },
                {
                  checked: true,
                  elementIdentifier: 'issuing_authority',
                  enabled: true,
                  id: 'issuing_authorityDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Issuing authority',
                  value: 'Test QEAA issuer',
                },
                {
                  checked: true,
                  elementIdentifier: 'document_number',
                  enabled: true,
                  id: 'document_numberDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Licence number',
                  value: 'WE000109',
                },
                {
                  checked: true,
                  elementIdentifier: 'portrait',
                  enabled: true,
                  id: 'portraitDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Portrait of mDL holder',
                  value: '_9jY__Z',
                },
                {
                  checked: true,
                  elementIdentifier: 'driving_privileges',
                  enabled: true,
                  id: 'driving_privilegesDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'Categories of vehicles',
                  value:
                    'sign: 10.02\nvalue: \nsign: 25.01\nvalue: \nsign: 03.02bd\nvalue: \nissue_date: 1992-03-01\nexpiry_date: 2026-05-05\nvehicle_category_code: B\nsign: 10.02\nvalue: \nsign: 25.01\nvalue: \nsign: 03.02bd\nvalue: \nissue_date: 2011-04-29\nexpiry_date: 2026-05-05\nvehicle_category_code: BE\nsign: 10.02\nvalue: \nsign: 25.01\nvalue: \nsign: 95\nvalue: . 05.05.2026.\nsign: 03.02bd\nvalue: \nissue_date: 1992-03-01\nexpiry_date: 2026-05-05\nvehicle_category_code: C\nsign: 10.02\nvalue: \nsign: 25.01\nvalue: \nsign: 95\nvalue: . 05.05.2026.\nsign: 03.02bd\nvalue: \nissue_date: 2011-04-29\nexpiry_date: 2026-05-05\nvehicle_category_code: CE\nsign: 10.02\nvalue: \nsign: 25.01\nvalue: \nsign: 95\nvalue: . 05.05.2026.\nsign: 03.02bd\nvalue: \nissue_date: 1992-02-01\nexpiry_date: 2026-05-05\nvehicle_category_code: D\nsign: 10.02\nvalue: \nsign: 25.01\nvalue: \nsign: 95\nvalue: . 05.05.2026.\nsign: 03.02bd\nvalue: \nissue_date: 2011-04-29\nexpiry_date: 2026-05-05\nvehicle_category_code: DE\nsign: 03.02bd\nvalue: \nissue_date: 1985-10-01\nexpiry_date: 2026-05-05\nvehicle_category_code: TROL',
                },
                {
                  checked: true,
                  elementIdentifier: 'un_distinguishing_sign',
                  enabled: true,
                  id: 'un_distinguishing_signDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'UN distinguishing sign',
                  value: 'LV',
                },
                {
                  checked: false,
                  elementIdentifier: 'administrative_number',
                  enabled: false,
                  id: 'administrative_numberDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'administrative_number',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'sex',
                  enabled: false,
                  id: 'sexDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'sex',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'height',
                  enabled: false,
                  id: 'heightDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'height',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'weight',
                  enabled: false,
                  id: 'weightDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'weight',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'eye_colour',
                  enabled: false,
                  id: 'eye_colourDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'eye_colour',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'hair_colour',
                  enabled: false,
                  id: 'hair_colourDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'hair_colour',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'birth_place',
                  enabled: false,
                  id: 'birth_placeDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'birth_place',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_address',
                  enabled: false,
                  id: 'resident_addressDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'resident_address',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'portrait_capture_date',
                  enabled: false,
                  id: 'portrait_capture_dateDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'portrait_capture_date',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'nationality',
                  enabled: false,
                  id: 'nationalityDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'nationality',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_city',
                  enabled: false,
                  id: 'resident_cityDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'resident_city',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_state',
                  enabled: false,
                  id: 'resident_stateDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'resident_state',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_postal_code',
                  enabled: false,
                  id: 'resident_postal_codeDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'resident_postal_code',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'resident_country',
                  enabled: false,
                  id: 'resident_countryDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'resident_country',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'family_name_national_character',
                  enabled: false,
                  id: 'family_name_national_characterDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'family_name_national_character',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'given_name_national_character',
                  enabled: false,
                  id: 'given_name_national_characterDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'given_name_national_character',
                  value: 'Not available',
                },
                {
                  checked: false,
                  elementIdentifier: 'signature_usual_mark',
                  enabled: false,
                  id: 'signature_usual_markDocument_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                  isRequired: false,
                  readableName: 'signature_usual_mark',
                  value: 'Not available',
                },
              ],
              title: 'mDL',
              meta: {
                id: 'Document_EudiWalletDocumentManager_061842b9-a2c0-4c9b-953b-49e3bc5e5d4b',
                type: 'mDL',
                issuanceState: 'Issued',
                hasExpired: false,
                expirationDate: '2025-04-25',
                issuingAuthority: 'Test QEAA issuer',
                issuerCountry: 'LV',
                issuanceDate: '2025-01-29',
              },
            },
          ],
          transactionData: {
            paymentId: 'string',
            amount: '0.08',
            currency: 'EUR',
            creditor: 'Merchant Test',
            purpose: 'Payment for the purchase of a product',
          },
        },
        error: 'string?',
      },
    },
    getRequestDocuments2: {
      request: {
        id: 'string',
        func: 'getRequestDocuments',
        data: null,
      },
      response: {
        id: 'string',
        status: 'SUCCESS',
        data: {
          verifierName: 'EUDI Remote Verifier',
          verifierIsTrusted: true,
          documents: [
            {
              title: 'mDL',
            },
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLfamily_nameDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Family name',
              value: 'Janis',
              checked: true,
              enabled: true,
              elementIdentifier: 'family_name',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLgiven_nameDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Given names',
              value: 'Liepa',
              checked: true,
              enabled: true,
              elementIdentifier: 'given_name',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLbirth_dateDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Date of birth',
              value: '2025-01-27',
              checked: true,
              enabled: true,
              elementIdentifier: 'birth_date',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLissue_dateDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Date of issue',
              value: '2025-01-27',
              checked: true,
              enabled: true,
              elementIdentifier: 'issue_date',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLexpiry_dateDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Date when mDL expires',
              value: '2025-02-03',
              checked: true,
              enabled: true,
              elementIdentifier: 'expiry_date',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLage_over_18Document_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Age attestation: Nearest “true” attestation above request',
              value: 'false',
              checked: true,
              enabled: true,
              elementIdentifier: 'age_over_18',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLage_over_21Document_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'age_over_21',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'age_over_21',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLage_in_yearsDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'age_in_years',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'age_in_years',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLage_birth_yearDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'age_birth_year',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'age_birth_year',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLissuing_authorityDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Issuing authority',
              value: 'Test MDL issuer',
              checked: true,
              enabled: true,
              elementIdentifier: 'issuing_authority',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLdocument_numberDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Licence number',
              value: '4343432',
              checked: true,
              enabled: true,
              elementIdentifier: 'document_number',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLportraitDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Portrait of mDL holder',
              value:
                '9j_4AAQSkZJRgABAQIAJQAlAAD_4QBiRXhpZgAATU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAMAAAITAAMAAAABAAEAAAAAAAAAAAAlAAAAAQAAACUAAAAB_9sAQwADAgICAgIDAgICAwMDAwQGBAQEBAQIBgYFBgkICgoJCAkJCgwPDAoLDgsJCQ0RDQ4PEBAREAoMEhMSEBMPEBAQ_8AACwgBsQFoAQERAP_EAB4AAQABBAMBAQAAAAAAAAAAAAABAgcICQMEBgoF_8QASRAAAQMDAwMCBQAHBAYGCwAAAQACAwQFEQYHEgghMQlBEyJRYXEUIzJCUoGRFWJyshgzOHWCwhZDobHR8CQlJjQ1REaFs8PU_9oACAEBAAA_ANqL_ZSPClERERERERERERERERERERERERERERUv9vypHhSiIiIiIiIi4Q93_k5I_Psvy7_qiw6Vtk961LfaG1W-mbzmqq2pZTwsbj9oveQGjse5IH3Vir16hnRpYq6S31u_thfNE7DjSRVNXFn7SQxPa4fgrqD1J-iR_wCxvxbj_wDa7gP_ANC_E1f6pPRhpaifUUu51VqCpa3Io7RZqt8z_wAOljZEP-J4Vuz60HS04fq9GbnfztND_wD2LyJ9bDa4ainp27M6pdYW5-BXfp8H6U_s0_NT44M7kj_Wu8L8mq9bvTUdZPHQ9Pd1nphK4QSS6jjje6MeHOYKd3B31bycB7OXYqfW30T-kUYpNi72ad7miqfLeImvYD5MYbE4Px93NVwZ_WQ6WYqlsAse4UzBHHI-aC1Uvw2lzWuMeX1IcXMyWO-XBcxxa4tw53vtLeqP0YanjgbNunPY6mVveC6WesiLHfwue2N0Y_Iesk9F670luLYabVWhtTW--WirGYauhnbLE7_ibnv9shejRERERERERERUv9vypHhSiIiIiIijIX5V6vtu07bKq9Xy501voKCB9TU1NRK2KGGJgy973uOGtaO5JIA8Ela5t5vWY0pp7UE9j2W0B_0opaaV0ZutxqX00VRxdjMUQHMtJ_ZLi0keWrEDfD1N-pzeCpMNs1M3RVoc3j-gWF5j5fd8zsyH-RasbNS7n7k6ypP7P1buHqS90jZPitguN1nqYw-INkcRnv5XmCSexPhEySMEnAQEjwSnJx8uP8AVTyd_Ef6pyd3-Y9_Pfyge8Yw89vHfwo5O-pVydpuoPenZKsM-1m4d3sTXSfEkpoJS6CQ_V0Tg5hP5C2JdNnrERzPp9MdS1mFO48YxqK0U5c0Euxymp25-UDuXMz_AIXLZbpTWGntb2Ci1TpC_Ul5s9yiZNSV1FM2aCVjs9w9p748HuDkY_aBC_fyFKIiIiIiIiKl_t-VI8KURERERRkfVdK43KitlHLcLhcKekpIGfFlmnlDGMZ_E5xIDR9z2WIPUJ6oPTxs02W1aSvTNf6gAcBTWWpa-lheOwEtSAYwM-zC4_XitPu8PUzvPvdqC63vWuvr1LT3Ob4ptcddIyiiZz5RxthDuBDfqRlWlyfGShJPknsiIiIiIiZP1VTXuJ7uJ8nz9fKvv0zdXe7_AEwaghuGjL1UVFikmDq6xVUhdSVLB-3huPkecftNwR75W7jpv6v9nOp2xCs0BqNkd7hjY64WKsIiraJ3FvLLCf1rORAD4-QPIAlrsht9GOLhnPnwqh4UoiIiIiIipf7flSPClERERFB8K12_m_m33Ttt_Xbg7hXcU9NSjFNSxvBqK6Y_sxRM8kl2AfZoBJ-UFaZOsT1B9fdVdJT6Uo7QNK6UpZnSuoYKovfWOPYGd_ytOG_ugYysRnPz4Kjk7OeRz9cqEREREREREU83YI5HBxkZ8r9vSurNS6HvtLqXSN7rbNdaJwkgq6SZ0U0Z98EHJB75Hus_Omz1dtyNJV9Hp7qApRqqxktjddKSJkdxp2-73BoDJh3OR8rhjsVte2z3R0JvFouh17ttqilvlkr2coqmne5pYWn5mPY4B0cjT-0x7Q4HsQAvYZb9VUiIiIiIipf7flSPClERERF4vdXdLR-zWgLzuVr28C32ayUxnne7HKR2QGRRtP7Ukji1jWeSXADHcrQj1k9WN16rtxo9WSWR1ms1ugNLbaAzukw3k4mR_fjzcCMhoAGBhY85I8EoiIiIiIiIiIiZOMZU8nYI5HBOSMq-nS71abldK-sf7b0VXGostdLH_a1kmcTTVjB5IHlkgGeLx3GRnK3v9P3UJt51Jbe0e4e3V1E8M2I62ieQKi3VAALoZmeWuwcg-HN4ubkOBN0g5rhkFVIiIiIiKl_t-VI8KURERF1pKhkeXukwG-SQcAfnOMDySfZaS_U96vnb27iO2m0TdXS6K0hUPY-SneTDX1wy18vbs5rAXNaT7lx-iwU5HOcnP1RERERERERERERE5H6lXn6Yep3X_S3uFHrjRtQailnaIbpapXEQ3CnySQ7HhwJPF3kZOFvq6c-oHRPUttbQboaFndHT1DjTV1HKQZrfWMDTJBJjsDhzHA-C17XeCALroiIiIiKl_t-VI8KURERFrd9UPreOgbTV9O21l1lh1LdIf_aC4U7-JoqRzDmna7yJXjHI-zPl8uHHT2ZHZJ8E-VSiIiIiIiIiIiIiIp5OHhx_qspegrq6uvSzueyS4zSz6K1G-OmvlKCeMBzgVTR_EweR7sJ_hC36W250d2oKa522qZU0tZEyeGVjgQ-N4Ba4Y7EEEH-a7yIiIiIqX-35UjwpRERF1KqshoKeWsq52xQQsdJJI92A1gBJJz2wACST9F81fUHraPcXfLXWuKOsdWU13vlZUU0_f9ZAJSI3j6Dg1uPsrbIiIiIiIiIiIiIiIiqD3e3t2W5n0jepiu3J23r9kNVVj57toWJklrnleC6W2PPFsZ9_1TsN_wALox4C2GoiIiIipf7flSPClEREWIXqi7nXvbDpJv79P1bqWr1VXU2nDO1-HMhna90wb75dFDI37CRx8gLQq4nx7fRQiIiIiIiIiIiIiIiIskugzqEh6dOoexasulVwsN2YbPeXPGGx00zwBIT7CNwZJgecFfQZSVcVZBHVU0okgmjbJG9juTS0jIcD75BBXaRERERUv9vypHhSiIiLU960u7sNZdNE7JUTnl1vEl-uAz8vKRpjhbjxkN59_wC-tXCIiIiIiIiIiIiIiIiKQ5w8OI9_K3--nJv1Qb5dNFha74kd60bHFpy6xySc3ySQwsMdQCe_GVhae_hwkb4asqkREREVL_b8qR4UoiIi0ber-T_pcTDPjT9v_wArlhAiIiIiIiIiIiIiIiIiLZF6K2sqm3bua60BLWsbRXqwxXFkLnY-JPTzhgLR9fhzSE_YLcKCD4KlERERUv8Ab8qR4UoiIi0besAT_pczdv8A6ft_-VywgRERERERERERERERERFkF0Kbnt2m6p9Bamq68UlBUXFtrrpSwvAgqmmEjiO-fmAz7eV9EDMeGuOCBj8fUELmREREVL_b8qR4UoiIi0besAR_pcz-f_gFv_yuWECIiIiIiIiIiIiIiIiIuSnnnp5o56eZ8UsTg-N7HFrmuB7EEeCPqvpd6fNbU24uymiNb0tQ6Vl4sVJUF7hhxcY2h-e5-bkDkexJHsrjoiIiKl_t-VI8KURERaNvV_8A9rmb_cFD_lcsIERERERERERERERERERS3yt43pBatOoekdljfE9h0xqS4Wscz2c14jqwQP3R_wClHt9QSs4URERFS_2_KkeFKIiItG_rAf7XE3-4Lf8A5XLB9EREREREREREREREREUt8ra56I2pbu-3bqaPkqy61001rucFO5o4x1ErZ45XNI8l7IYgQfHwxj95bS0RERFS_wBvypHhSiIiLRt6wP8Atcz_AO4Lf_lcsIERERERERERERERERERFnr6P-5dZo_qRr9BTOlFHrWzTQFpIDG1FMfixyHIySGiZgwcD4hJBwt17Hl2Sexb7LkRERFS_',
              checked: true,
              enabled: true,
              elementIdentifier: 'portrait',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLdriving_privilegesDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'Categories of vehicles',
              value: 'issue_date: 27 Jan 2025\nexpiry_date: 27 Jan 2025\nvehicle_category_code: AM',
              checked: true,
              enabled: true,
              elementIdentifier: 'driving_privileges',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLun_distinguishing_signDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'UN distinguishing sign',
              value: 'FC',
              checked: true,
              enabled: true,
              elementIdentifier: 'un_distinguishing_sign',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLadministrative_numberDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'administrative_number',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'administrative_number',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLsexDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'sex',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'sex',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLheightDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'height',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'height',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLweightDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'weight',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'weight',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLeye_colourDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'eye_colour',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'eye_colour',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLhair_colourDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'hair_colour',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'hair_colour',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLbirth_placeDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'birth_place',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'birth_place',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLresident_addressDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'resident_address',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'resident_address',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLportrait_capture_dateDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'portrait_capture_date',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'portrait_capture_date',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLnationalityDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'nationality',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'nationality',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLresident_cityDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'resident_city',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'resident_city',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLresident_stateDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'resident_state',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'resident_state',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLresident_postal_codeDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'resident_postal_code',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'resident_postal_code',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLresident_countryDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'resident_country',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'resident_country',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLfamily_name_national_characterDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'family_name_national_character',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'family_name_national_character',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLgiven_name_national_characterDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'given_name_national_character',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'given_name_national_character',
            },
            {},
            {},
            {},
            {
              id: 'org.iso.18013.5.1.mDLsignature_usual_markDocument_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              readableName: 'signature_usual_mark',
              value: 'Not available',
              checked: false,
              enabled: false,
              elementIdentifier: 'signature_usual_mark',
            },
            {},
          ],
        },
        error: 'string?',
      },
    },
    getTransactions: {
      request: {
        id: 'string',
        func: 'getTransactions',
        data: {
          documentId: 'string',
        },
      },
      response: {
        id: 'string',
        status: 'success|error',
        data: {
          transactions: [
            {
              docType: 'eu.europa.ec.eudi.pid.1',
              documentId: 'Document_EudiWalletDocumentManager_6800ceac-ddbe-4fb3-88bb-37c23e5e2b76',
              eventType: 'DOCUMENT_PRESENTED',
              id: 'ef1c8b5e-9b9a-41b5-837e-2d517fe0f96a',
              nameSpace: 'PID',
              status: 'SUCCESS',
              timestamp: 1737987746164,
            },
            {
              docType: 'org.iso.18013.5.1.mDL',
              documentId: 'Document_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              eventType: 'DOCUMENT_ISSUED',
              id: 'ea4bd5fd-b74e-45a5-a443-020311912cd8',
              nameSpace: 'mDL',
              status: 'SUCCESS',
              timestamp: 1737987746174,
            },
            {
              docType: 'org.iso.18013.5.1.mDL',
              documentId: 'Document_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              eventType: 'DOCUMENT_DELETED',
              id: 'ea4bd5fd-b74e-45a5-a443-020311912cd82',
              nameSpace: 'mDL',
              status: 'ERROR',
              timestamp: 1737987746174,
            },
            {
              docType: 'org.iso.18013.5.1.mDL',
              documentId: 'Document_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f6',
              eventType: 'DOCUMENT_SIGNED',
              id: 'ea4bd5fd-b74e-45a5-a443-020311912cd82',
              nameSpace: 'eSign',
              status: 'ERROR',
              timestamp: 1737987746174,
              authority: 'LVRTC',
            },
            {
              docType: 'org.iso.18013.5.11.mDL',
              documentId:
                'Document_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f61',
              eventType: 'DOCUMENT_PAYMENT',
              id: 'ea4bd5fd-b74e-45a5-a443-020311912cd82',
              nameSpace: 'mDL',
              status: 'ERROR',
              timestamp: 1737987746174,
            },
            {
              docType: 'org.iso.18013.5.1.mDL',
              documentId:
                'Document_EudiWalletDocumentManager_e1bded50-d542-4bbf-88ab-e059209264f61',
              eventType: 'test',
              id: 'ea4bd5fd-b74e-45a5-a443-020311912cd82',
              nameSpace: 'mDL',
              status: 'ERROR',
              timestamp: 1737987746174,
              authority: 'Test issuer',
            },
          ],
        },
      },
    },
    resolveDocumentOffer: {
      response: {
        id: 'string',
        status: 'SUCCESS',
        data: {
          documents: [
            {
              title: 'mDL',
            },
            {
              title: 'PID',
            },
          ],
          issuerName: 'edim-demo-issuer-dev.example.lv',
          txCodeLength: 5,
        },
      },
    },
    getOfferCodeData: {
      response: {
        id: 'string',
        status: 'SUCCESS',
        data: {
          issuerName: 'edim-demo-issuer-dev.example.lv',
          txCodeLength: 5,
          offerUri:
            'openid-credential-offer://credential_offer?credential_offer\u003d%7B%22credential_issuer%22:%20%22https://edim-demo-issuer-dev.example.lv%22%2C%20%22credential_configuration_ids%22:%20%5B%22eu.europa.ec.eudi.mdl_mdoc%22%2C%20%22eu.europa.ec.eudi.pid_mdoc%22%5D%2C%20%22grants%22:%20%7B%22urn:ietf:params:oauth:grant-type:pre-authorized_code%22:%20%7B%22pre-authorized_code%22:%20%2283d7bac2-c1c9-45b9-8b77-c1d7b14334b3%22%2C%20%22tx_code%22:%20%7B%22length%22:%205%2C%20%22input_mode%22:%20%22numeric%22%2C%20%22description%22:%20%22Please%20provide%20the%20one-time%20code.%22%7D%7D%7D%7D',
        },
      },
    },
    getUserSignOptions: {
      request: {
        id: 'string',
        func: 'getUserSignatureOptions',
        data: null,
      },
      response: {
        id: 'string',
        status: 'SUCCESS',
        data: {
          options: {
            eSign: [
              {
                id: 'string',
                name: 'E-Sign',
                expiresOn: '2028-03-05T11:49:10',
                issuedOn: '2025-03-05T11:49:10',
                type: 'eSign',
              },
              {
                id: 'string1',
                name: 'E-Sign',
                expiresOn: '2028-03-05T11:49:10',
                issuedOn: '2025-03-05T11:49:10',
                type: 'eSign',
              },
            ],
            eSeal: [
              {
                id: 'string',
                name: 'E-Seal',
                expiresOn: '2028-03-05T11:49:10',
                issuedOn: '2025-03-05T11:49:10',
                type: 'eSeal',
              },
            ],
          },
        },
      },
    },
    pickFiles: {
      request: {
        id: 'string',
        func: 'pickFiles',
        data: {},
      },
      response: {
        id: 'string',
        status: 'success|error',
        data: {
          files: [
            {
              path: '/path/to/file.pdf', // e.g. "/path/to/file.pdf"
              name: 'file.pdf', // e.g. "file.pdf"
              size: '888', // in bytes
              type: '.pdf', // e.g .pdf, .docx
              isContainer: true, // e.g .edoc, .asice
              isValid: true, // invalid if file over 25 MB
              containerInfo: {
                // if isContainer is true
                signers: [
                  {
                    name: 'Test Testiņš',
                    signedAt: '2025-03-07T09:58:13Z',
                    type: 'eSign', // eSign, eSeal, testESign
                  },
                  {
                    name: 'Māra Paraudziņa',
                    signedAt: '2025-03-07T09:58:13Z',
                    type: 'eSeal', // eSign, eSeal, testESign
                  },
                  {
                    name: 'Māris Paraudziņš',
                    signedAt: '2025-03-07T09:58:13Z',
                    type: 'testESign', // eSign, eSeal, testESign
                  },
                ],
                files: [
                  {
                    name: 'file.docx',
                  },
                  {
                    name: 'test.pptx',
                  },
                ],
              },
            },
          ],
        },
      },
    },
    getSigningMethods: {
      request: {
        id: 'string',
        func: 'getSigningMethods',
        data: null,
      },
      response: {
        id: 'string',
        status: 'success|error',
        data: {
          // Same data as in getUserSignOptions, tbd
          methods: [
            {
              meta: {
                id: 'Document_EudiWalletDocumentManager_a67bd590-b31d-4348-b60e-54b31e5da796',
                issuanceState: 'Issued',
                type: 'eSign',
                hasExpired: false,
                isFavorite: true,
                expirationDate: '2025-11-04T12:05:52+01:00',
                issuingAuthority: '',
                issuerCountry: '',
                issuanceDate: '2024-11-04T12:05:52+01:00',
                displayNumber: '545353543',
                description: '',
                additionalInfo: '',
              },
            },
            {
              meta: {
                id: 'Document_EudiWalletDocumentManager_a67bd590-b31d-4348-b60e-54b31e5da755',
                issuanceState: 'Issued',
                type: 'eSeal',
                hasExpired: false,
                isFavorite: true,
                expirationDate: '2025-11-04T12:05:52+01:00',
                issuingAuthority: '',
                issuerCountry: '',
                issuanceDate: '2024-11-04T12:05:52+01:00',
                displayNumber: '545353543',
                description: '',
                additionalInfo: '',
              },
            },
          ],
        },
      },
    },
    getState: {
      request: {
        id: 'string',
        func: 'getState',
        data: null,
      },
      response: {
        id: 'string',
        status: 'SUCCESS',
        data: {
          theme: 'string', // light | dark | system
          language: 'lv', // en | lv
          fullName: 'Test Testiņš',
          system: 'android', // android | ios
        },
      },
    },
    getBiometricAvailability: {
      request: {
        id: 'string',
        func: 'getBiometricAvailability',
        data: {},
      },
      response: {
        id: 'string',
        status: 'SUCCESS',
        data: {
          type: 'android', // "touchId", "faceId", "android", "exists", null
        },
      },
    },
  }),
  getters: {
    getDocumentDetailsGetter: (state) => (id) =>
      state.getDocumentDetails?.response?.find((item) => item.data.meta.id === id),
  },
  actions: {
    deleteDocument(params) {
      this.getDocuments.response.data.documents = this.getDocuments.response.data.documents.filter(
        (item) => item.id !== params
      );
    },
  },
});
